#!/usr/bin/env bash
# Configures localhost and facebook.com IP address mappings
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts
sed -i '/[[:space:]]facebook\.com\([[:space:]]\|$\)/d' /etc/hosts
printf '%s\n' '8.8.8.8 facebook.com' >> /etc/hosts
