#!/usr/bin/env bash
# Configures localhost and facebook.com IP address mappings
temp_file=$(mktemp)

awk '
{
    facebook=0
    for (i = 2; i <= NF; i++) {
        if ($i == "localhost")
            $1 = "127.0.0.2"
        if ($i == "facebook.com")
            facebook=1
    }
    if (facebook == 0)
        print
}
END {
    print "8.8.8.8 facebook.com"
}
' /etc/hosts > "$temp_file"

cat "$temp_file" > /etc/hosts
rm "$temp_file"
